basic:
    name: 'https://rockinjump.com/'
    environments:
        production: 'https://rockinjump.com/'
        staging: 'https://ext7dvybjp.wpdns.site/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: null
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /contact-us
        - /park-locations
        - /birthday-party
        - /indoor-attractions
        - /about-us
        - /cleanliness
        - /join-our-team
        - /terms-of-use
        - /safety
        - /jumpsafe
        - /privacy-policy
        - /feed
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
